### ISSUE TITLE
Data integrity

### ISSUE THREAD

**Issue by kod-kristoff** [spraakbanken/karp-backend-v5#24]
Check consistency on data on lexicon level, similar to how the  `autoupdate` decorator works.
- [ ] When updating document through backend
- [ ] When adding new document through backend (also generate)
- [ ] When adding documents from server
