### ISSUE TITLE
Rewrite extra_source so that all supported sources are separate decorators

### ISSUE THREAD

**Issue by kod-kristoff** [spraakbanken/karp-backend-v5#30]
- [ ] Write decorators for all supported extra_source functions.
- [ ] Document when and how they are called
- [ ] For `format` extra sources, enable querying the backend of what formats are available.

Examples:
```python
@ext.format({'<resource1>': ['html', 'tsv']})
@ext.format({'<resource2>': 'html'})
def function_named_freely(...):
  ...
```
